### PR TITLE
.Net Core 1.0 RC2 support

### PR DESCRIPTION
**Pull request by jonstoneman**
The DocoptNet project targets netstandard1.5 and net40.  They other projects have not been updated and reference the net40 version of DocoptNet.dll.

csproj -> xproj project references were not working properly for me (they are meant to with RC2) so I've referenced the configuration appropriate assemblies:

```
<Reference Include="docopt.net">
  <HintPath>..\..\DocoptNet\bin\$(Configuration)\net40\DocoptNet.dll</HintPath>
</Reference>
```

I also had to force a build of the DocoptNet project in `Build.bat` as MSBuild was building it last:

```
dotnet restore %BUILDIR%\..\src\DocoptNet 
dotnet build %BUILDIR%\..\src\DocoptNet -c Release
```

Finally, the nuspec references the dll/pdb files in `/src` rather than `/_build`.

Hopefully all these issues will go away with the upcoming xproj -> csproj change in .Net Core.

### CODE REVIEW

**Comment by jonstoneman** [comment]
It appears that the following workaround is required until AppVeyor supports .Net Core 1.0 RC2: https://blog.tommyparnell.com/use-dotnet-rc2-with-appveyor/

**Comment by voieducode** [comment]
Applying the appveyor workaround now

**Comment by voieducode** [comment]
Thank you for this. This will address issue #22.

**Comment by giggio** [comment]
Nice to see that there were pretty much no changes to the C# code.

**Comment by voieducode** [comment]
I have just published the package.

**Comment by giggio** [comment]
Nice, congrats!

**Pull request merged**
