### PR TITLE
Replace `ValueObject` with simply `object`

### PR DESCRIPTION
**Pull request by atifaziz**
This PR is probably a controversial (for compatibility reasons) and a sweeping change as it proposes to remove `ValueObject` and replace it with just `object`. The arguments for its removal are as follows:

- `ValueObject` is a `class` and causes an additional allocation per value. Converting it to a `struct` will require quite some review without much added benefits except saving on the wrapper allocation.
- `Add` member of `ValueObject` was used in just one place and could be in-lined at the single call site or moved to `LeafPattern`; the latter was chosen. `Add` was the only reason `ValueObject` was read-write.
- Equality members like `Equals` and `GetHashCode` were never used or needed.
- It doesn't make the wrapped value any more strong-typed than using the bare `object`; instead it does conversions in some cases that can fail.
- A `ValueObject` reference that can be null or an instance with a `null` for `Value` adds confusing semantics at best.
- Modern C# features like pattern matching are equally effective at succinctly encoding decisions based on type checks.

All tests still pass.

### CODE REVIEW

**Comment by smoothdeveloper** [comment]
@atifaziz not sure if it affects consumers of the library or if it is an implementation detail that doesn't leak.

If the former, does it make it easier to consume in non C# languages consuming the library?

**Comment by smoothdeveloper** [comment]
If the end goal is to allow passing values such as whatever could be passed as constructor of `ValueObject`, I would suggest to allow implicit conversion operator on it instead of changing all the checks, as a first step (it would allow to make the updated test pass).

Also, I'm not sure what is the approach similar to [F# active patterns](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/active-patterns) in today's C#, but it seems encapsulating the various "is shape of object matching this criteria" in something similar would ease the maintenance and reasoning about the wild array of dynamic checks being expanded adhoc.

`ValueObject` offers a bit of a statically typed API helping to reason about those things, while adhoc pattern matching makes it harder to reason about IMO.

I'm mostly used to pattern matching in F#, where it increases the type safety and ability to reason about changes, here it seems to not do that compared to previous API in the implementation detail, from a cursory look.

Is exposing `object` in public C# API because it gained some pattern matching ability a trend for cases of replacing opaque values in libraries?

This is just an opinion and probably missing on some of the merit of the changes.

To reason about the changes and later addition to the idioms proposed here, I'd suggest having internal extension methods on `object` achieving what was part of `ValueObject` API, it will minimize the diff, and probably achieve some of the things I'm relating about wrt active patterns.

**Comment by smoothdeveloper** [comment]
@atifaziz question: if you had Discriminated Unions available in C#, would you go with naked `object` rather than defining the finite set of possible cases this type ends up having at runtime currently?

In meantime, it would be interesting to compare a refactor using F# to define that type:
```fsharp
type ValueObject =
  | BoolValue of bool
  | StringValue of string
  | ListValue of ResizeArray<ValueObject>
  // ...
  member x.IsTrue =
    match x with
    | BoolValue b -> b
    | StringValue _ | ListValue _ -> false
  member x.IsFalse = not x.IsTrue
  // ...
```

Lots of things would come for free (comparing/equality), this PR is interesting thought exercise :)

> Converting it to a struct will require quite some review without much added benefits except saving on the wrapper allocation.

Also, is the concern of allocation for those significant for your use case? if that's minor compared to allowing implicit conversions to reach what I believe was the main goal in terms of client code, I think a discriminated union, even hand desugared in C# solely, would still be better route for the long term maintenance than just `object`, no matter how expressive the pattern matching constructs are nowadays.

**Comment by atifaziz** [comment]
@smoothdeveloper Thanks a ton for your comments, thoughts, challenges and ideas! Your feedback has made me rethink a little bit and I spiked another approach late last night. I think I might have something even better to propose with, what I like to call, a BYOT (bring your own types) strategy. I'll try and find some time this weekend (don't hold you breath) to clean-up the spike so it's in a good state to share here for further comment. My critique that `ValueObject` provides little benefit still stands since it's not needed for the internal operation. However, the new approach won't require its removal from the public API and so we could afford to maintain backward compatibility.

**Comment by atifaziz** [comment]
Closing as it's been superseded by PR #104.

**Pull request closed without merging**
