### PR TITLE
Support for dashes in T4 generation (converting dashes to camel case)

### PR DESCRIPTION
**Pull request by jefim**
Hi,

I think that the title says it all. I added dash support and one simple unit test for it. This way I can use dashes in docopt usages like "do-something" and they will look fine in the code generated by the T4 template.

Best,
Jefim

### CODE REVIEW

**Comment by voieducode** [comment]
Hey @jefim thanks for the PR. Please check out my comments.

**Comment by jefim** [comment]
Good remarks. Here is a new commit where I tried to address the issues that you pointed out. If you have any other comments - feel free to add them.

**Comment by voieducode** [comment]
Many thanks for the PR @jefim!

**Comment by jefim** [comment]
Glad I could help.

**Pull request merged**
