### PR TITLE
Upgrade Project to new `.csproj`

### PR DESCRIPTION
**Pull request by iwillspeak**
This is needed to build now. Should fix problem where the library was
linked to the `-rc2` version of .NET Standard.

### CODE REVIEW

**Comment by voieducode** [comment]
Thanks for this!

**Comment by voieducode** [comment]
That fails in the CI box:
Build started
git clone -q --branch=master https://github.com/docopt/docopt.net.git C:\projects\docopt-net
git checkout -qf 0c1dbe5ad4524a7b52140fff09ff1d24e11d08f8
(new-object net.webclient).DownloadFile('https://download.microsoft.com/download/4/6/1/46116DFF-29F9-4FF8-94BF-F9BE05BE263B/packages/DotNetCore.1.0.0.RC2-SDK.Preview1-x64.exe','core.exe')
    core.exe /install /quiet /norestart
    dotnet restore
MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.
Command exited with code 1

**Comment by iwillspeak** [comment]
What script is the CI server running? That version of the SDK is quite old.

The plan with this PR was to fix a problem when loading Docopt via reflection which we traced down to being linked against the -RC2 sdk rather than the final release. Could you try updating the CI script and re-building with the latest dotnet SDK? Using 2.1.401 or whatever will still produce builds which are compatible with .NET Standard 1.5 with the target frameworks set the way that they are.

**Comment by iwillspeak** [comment]
The build script I can find in this repo (`build/Build.bat`) doesn't seem to match up with the output in your comment.

**Comment by voieducode** [comment]
I use appveyor so I think it is just trying to pick up a project file

**Comment by iwillspeak** [comment]
Could you share the appveyor config please, or check it in to this repo so that I can have a go fixing it?

**Comment by voieducode** [comment]
Even better, I think I can add you to the project if you are happy to DM me
you email.

**Pull request merged**
